version: "3"
services:
  api-link-hub:
    image: bitnami/postgresql
    ports:
      - 2020:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apiLinkHub
